### ISSUE TITLE
mario sunshine from nintendo switch update 1.1.1

### ISSUE THREAD

**Issue by heraldo1980** [JoshuaMKW/pyisotools#11]
This Rom came with something different from the normal GameCube ISOs, Nintendo made it on purpose, I really wanted to work on this game to translate it into my language, but I can't unpack the ROM because it's different from the others, could you take a look for me and you would already add it to your tool, I will show you the errors and show you a way for you to have access to this ROM without piracy methods.

**Comment by heraldo1980** [comment]
The rom is here in this Xentax thread.
https://forum.xentax.com/viewtopic.php?t=26769

**Comment by JoshuaMKW** [comment]
The ISO you tried to provide was blocked by moderators so I can't access it, but the GCM is by definition not functional if my tool can't read it. Therefore I don't plan to support it.
