### ISSUE TITLE
Linux CLI doesn't recognize source arugment

### ISSUE THREAD

**Issue by NerduMiner** [JoshuaMKW/pyisotools#2]
With Python 3.9.1 on Manjaro Linux, the python CLI tool is unable to recognize the source argument.
There are two combinations of arguments I tried, each with different results:
![image](https://user-images.githubusercontent.com/23490112/106493042-a44f7c80-6486-11eb-9a86-55f5909aef25.png)
Using the order intended by the help parses the source iso argument as the job and errors out.
![image](https://user-images.githubusercontent.com/23490112/106493172-ca751c80-6486-11eb-9f32-307c495f9bcd.png)
However, supplying the job first and then the source iso argument shows the tool doesn't recognize the argument I am putting as the source. 
Supplying a destination argument doesn't change anything.  Running the tool without a source argument allows it to proceed but gets stuck as normal since it has nothing to work on.

**Comment by JoshuaMKW** [comment]
Turns out this bug is caused by an oversight in the argument process, I wasn't trimming out the executable path before passing to `argparse` for parsing!

A new release is coming soon, which will fix the issue. When it comes out for `pip`, you can upgrade your install :P
