### ISSUE TITLE
Opening Root folders made by Dolphin fails because of no .config.json

### ISSUE THREAD

**Issue by NerduMiner** [JoshuaMKW/pyisotools#3]
In a case when a root filesystem is made from an iso via Dolphin, it doesn't normally create a .config.json file and thus the file will either have to be created manually or the iso has to be extracted from pyisotools first. If the original iso cant be sourced for extraction, would it be possible for pyisotools to generate a config.json from an existing root folder?

**Comment by JoshuaMKW** [comment]
Yes, I'm aware of this bug and it will be fixed soon hopefully. I'm busy doing a rewrite for pyisotools, so for now simply making an empty file named .config.json in the root/sys folder should do the trick
